steps:
  - id: 'Pull latest cached image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/website:latest || exit 0']

  - id: 'Build new image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/website:latest',
        '-t',
        'gcr.io/$PROJECT_ID/website:$_NODE_ENV',
        '--cache-from',
        'gcr.io/$PROJECT_ID/website:latest',
        '.'
      ]

  - id: 'Push new image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/website:$_NODE_ENV']

  - id: 'Deploy container image to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      [
        '-c',
        'gcloud run deploy website-$_NODE_ENV --image gcr.io/$PROJECT_ID/website:$_NODE_ENV --region us-central1 --platform managed --allow-unauthenticated --set-env-vars NODE_ENV=$_NODE_ENV'
      ]

images:
  ['gcr.io/$PROJECT_ID/website:latest', 'gcr.io/$PROJECT_ID/website:$_NODE_ENV']
